apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-091648"
data:
  deployedAt: "2025-12-07 09:16:48Z"
  commit: "5675fad595ced56fa7a32e5552854a92740f7436"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20001824297"
  runNumber: "54"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20001824297"
