apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-081148"
data:
  deployedAt: "2025-12-07 08:11:48Z"
  commit: "bff254557a3a70eb91a7d75550e33f9f98f5031b"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20001132731"
  runNumber: "50"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20001132731"
