apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-133120"
data:
  deployedAt: "2025-12-07 13:31:20Z"
  commit: "bf73f0785e678f878efcbfcb34004a5bb69f6d10"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20004610885"
  runNumber: "62"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20004610885"
