apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-072056"
data:
  deployedAt: "2025-12-07 07:20:56Z"
  commit: "a651ccf5d13063b7667969acc405b292cb7c6c9c"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20000579345"
  runNumber: "48"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20000579345"
