apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-111916"
data:
  deployedAt: "2025-12-07 11:19:16Z"
  commit: "d7b059cb1a1fe5c80ac45481a1169b30f5a4ae48"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20003197188"
  runNumber: "59"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20003197188"
