apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-deploy-trigger
  namespace: wordpress-staging
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: staging
    deploy-time: "20251207-104739"
data:
  deployedAt: "2025-12-07 10:47:39Z"
  commit: "32f1022c5fe901724a06e07ce3d93520af17f9c0"
  commitShort: ""
  branch: "main"
  triggeredBy: "taha-salam"
  runId: "20002860889"
  runNumber: "58"
  pipelineUrl: "https://github.com/taha-salam/wordpress-cicd-project/actions/runs/20002860889"
